// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMz0kFZbVL4RmYBUWJzR6UaCFAJoVlSGE',
    appId: '1:95402712864:web:65209197dc4dfa46b3c145',
    messagingSenderId: '95402712864',
    projectId: 'wallpaper-app-flutter-151b8',
    authDomain: 'wallpaper-app-flutter-151b8.firebaseapp.com',
    storageBucket: 'wallpaper-app-flutter-151b8.appspot.com',
    measurementId: 'G-064R7W0ZG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXE4FANRO7syZVrcFKGgFIFomBHDy6mY',
    appId: '1:95402712864:android:2849157bdcb66076b3c145',
    messagingSenderId: '95402712864',
    projectId: 'wallpaper-app-flutter-151b8',
    storageBucket: 'wallpaper-app-flutter-151b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlAS1Fhmr5kj222pplumc2gRBvvuX0KKE',
    appId: '1:95402712864:ios:4a2db84b593e55bab3c145',
    messagingSenderId: '95402712864',
    projectId: 'wallpaper-app-flutter-151b8',
    storageBucket: 'wallpaper-app-flutter-151b8.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlAS1Fhmr5kj222pplumc2gRBvvuX0KKE',
    appId: '1:95402712864:ios:78e1b6d909abfdccb3c145',
    messagingSenderId: '95402712864',
    projectId: 'wallpaper-app-flutter-151b8',
    storageBucket: 'wallpaper-app-flutter-151b8.appspot.com',
    iosBundleId: 'com.example.wallpaperApp.RunnerTests',
  );
}
